### ISSUE TITLE
regular_type for rRUM

### ISSUE THREAD

**Issue by cwliu007** [alexanderrobitzsch/CDM#1]
Hi Alexander,

Thank you for the CDM package! I simulated RRUM data and found the following seems not working. The parameter estimates are out of range [0,1].

CDM::gdina(res,Q,skillclasses=Qpatterns,rule="RRUM",regular_type="scad", regular_lam=0);

I expect it should return the same estimates when not using regular_type.

**Comment by alexanderrobitzsch** [comment]
Am 2018-05-25 19:04, schrieb genwei007:
> Hi Alexander,
> 
> Thank you for the CDM package! I simulated RRUM data and found the
> following seems not working. The parameter estimates are out of range
> [0,1].
> 
> CDM::gdina(res,Q,skillclasses=Qpatterns,rule="RRUM",regular_type="scad",
> regular_lam=0);
> 
> I expect it should return the same estimates when not using 
> regular_type.


Technically, the coordinate decent algorithm is used when a value of a 
penalty is specified as an input. Without regularization parameters, 
joint estimation of item parameters is employed. I guess that this could 
be the reason.

**Comment by alexanderrobitzsch** [comment]
Another suggestion. I think it is better to use the ACDM model (with logit link) if regularized models are of interest. In general, the logit link is preferable (in my view) to the log link.

**Comment by cwliu007** [comment]
Hi Alexander,
Thanks for your reply! I'll take a close look at these models.

**Comment by cwliu007** [comment]
Hi Alexander,
I checked the help of CDM package about how to set the range of lambda, but it seems unclear as well as in the literature about Q matrix estimation. It seems the lambda range also depends on the model we use or sample size(?). Local maxima also appears a problem which may needs a lot of starting values to try on each lambda...

Thanks!

**Comment by alexanderrobitzsch** [comment]
I slightly changed the estimation algorithm using a majorizing function (work of Breheny and Huang) in the CDM 6.5 dev version. I had the impression that this improves estimation precision. Moreover, the penalty term is N*Pen(\lambda) so \lambda is thought to be sample size independent. However, of course, \lambda will typically depend on model size. I can only recommend to try a sufficiently large grid of \lambda values. Starting values can be a problem, but when I estimate models, I typically use ascending \lambda values and use the model parameters of the previously fitted model as an initial estimate. This could sometimes help. In the function `reglca` for regularized latent class analysis, I also allowed multiple starting values which is more critical for this model class compared to the GDINA model.

Alexander

**Comment by cwliu007** [comment]
Thank you, Alexander! Your comments are very useful and reasonable indeed.
