### ISSUE TITLE
 Max(X2) value = Nan

### ISSUE THREAD

**Issue by yjchen11** [alexanderrobitzsch/CDM#6]
Dear Author,
Thank you for the CDM package! I run a series of hierarchical models. Model fit for one hierarchical model does not produce Max(X2).  I'd appreciate if you could provide any guidance on this issue. Thank you!

Below is the code and output:
------Code------

#hierarchical relation among attributes: d5H9 
skill<-paste0("A",1:5) 
B<-"A4>A5"
sp1<-skillspace.hierarchy(B=B,skill.names = skill)
d5H9<- CDM::din(data = US,q.matrix=Q5,skillclasses=sp1$skillspace.reduced)
summary(d5H9)
d5H9fit<-modelfit.cor.din(d5H9,  jkunits=10)# Assessing model fit 
fit<-summary(d5H9fit)
classification<-cdm.est.class.accuracy(d5H9)$statistics[,c("Pa_est","Pc_est")] 

-----Output-----

> fit<-summary(d5H9fit)
Test of Global Model Fit
       type value   p
1   max(X2)   NaN NaN
2 abs(fcor)   0.7   0

Fit Statistics
                  est jkunits jk_est jk_se est_low est_upp
MADcor          0.092      10  0.057 0.006   0.045   0.069
SRMSR           0.117      10  0.076 0.008   0.060   0.092
100*MADRESIDCOV 1.785      10  1.158 0.124   0.915   1.400
MADQ3           0.096      10  0.047 0.003   0.042   0.052
MADaQ3          0.095      10  0.046 0.002   0.043   0.049

[Q5.txt](https://github.com/alexanderrobitzsch/CDM/files/6037323/Q5.txt)
[US.txt](https://github.com/alexanderrobitzsch/CDM/files/6037324/US.txt)

**Comment by alexanderrobitzsch** [comment]
Thank you for reporting. This was indeed a numerical issue and has been fixed in the recently ``CDM 7.6-4`` dev version that is now on Github.

**Comment by yjchen11** [comment]
Thank you so much for addressing this issue and making the new version available to the public!
